# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2020.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/q7frkz/Dev/Qt/Tuto2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/q7frkz/Dev/Qt/Tuto2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/q7frkz/Dev/Qt/Tuto2/CMakeFiles /home/q7frkz/Dev/Qt/Tuto2/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/q7frkz/Dev/Qt/Tuto2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tuto2

# Build rule for target.
Tuto2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tuto2
.PHONY : Tuto2

# fast build rule for target.
Tuto2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/build
.PHONY : Tuto2/fast

#=============================================================================
# Target rules for targets named Tuto2_autogen

# Build rule for target.
Tuto2_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tuto2_autogen
.PHONY : Tuto2_autogen

# fast build rule for target.
Tuto2_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2_autogen.dir/build.make CMakeFiles/Tuto2_autogen.dir/build
.PHONY : Tuto2_autogen/fast

BServer.o: BServer.cpp.o

.PHONY : BServer.o

# target to build an object file
BServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/BServer.cpp.o
.PHONY : BServer.cpp.o

BServer.i: BServer.cpp.i

.PHONY : BServer.i

# target to preprocess a source file
BServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/BServer.cpp.i
.PHONY : BServer.cpp.i

BServer.s: BServer.cpp.s

.PHONY : BServer.s

# target to generate assembly for a file
BServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/BServer.cpp.s
.PHONY : BServer.cpp.s

Bilberry.o: Bilberry.cpp.o

.PHONY : Bilberry.o

# target to build an object file
Bilberry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Bilberry.cpp.o
.PHONY : Bilberry.cpp.o

Bilberry.i: Bilberry.cpp.i

.PHONY : Bilberry.i

# target to preprocess a source file
Bilberry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Bilberry.cpp.i
.PHONY : Bilberry.cpp.i

Bilberry.s: Bilberry.cpp.s

.PHONY : Bilberry.s

# target to generate assembly for a file
Bilberry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Bilberry.cpp.s
.PHONY : Bilberry.cpp.s

GPSInfo.o: GPSInfo.cpp.o

.PHONY : GPSInfo.o

# target to build an object file
GPSInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/GPSInfo.cpp.o
.PHONY : GPSInfo.cpp.o

GPSInfo.i: GPSInfo.cpp.i

.PHONY : GPSInfo.i

# target to preprocess a source file
GPSInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/GPSInfo.cpp.i
.PHONY : GPSInfo.cpp.i

GPSInfo.s: GPSInfo.cpp.s

.PHONY : GPSInfo.s

# target to generate assembly for a file
GPSInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/GPSInfo.cpp.s
.PHONY : GPSInfo.cpp.s

LCDRange.o: LCDRange.cpp.o

.PHONY : LCDRange.o

# target to build an object file
LCDRange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/LCDRange.cpp.o
.PHONY : LCDRange.cpp.o

LCDRange.i: LCDRange.cpp.i

.PHONY : LCDRange.i

# target to preprocess a source file
LCDRange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/LCDRange.cpp.i
.PHONY : LCDRange.cpp.i

LCDRange.s: LCDRange.cpp.s

.PHONY : LCDRange.s

# target to generate assembly for a file
LCDRange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/LCDRange.cpp.s
.PHONY : LCDRange.cpp.s

Menu.o: Menu.cpp.o

.PHONY : Menu.o

# target to build an object file
Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Menu.cpp.o
.PHONY : Menu.cpp.o

Menu.i: Menu.cpp.i

.PHONY : Menu.i

# target to preprocess a source file
Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Menu.cpp.i
.PHONY : Menu.cpp.i

Menu.s: Menu.cpp.s

.PHONY : Menu.s

# target to generate assembly for a file
Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Menu.cpp.s
.PHONY : Menu.cpp.s

RGB.o: RGB.cpp.o

.PHONY : RGB.o

# target to build an object file
RGB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/RGB.cpp.o
.PHONY : RGB.cpp.o

RGB.i: RGB.cpp.i

.PHONY : RGB.i

# target to preprocess a source file
RGB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/RGB.cpp.i
.PHONY : RGB.cpp.i

RGB.s: RGB.cpp.s

.PHONY : RGB.s

# target to generate assembly for a file
RGB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/RGB.cpp.s
.PHONY : RGB.cpp.s

Tuto2_autogen/mocs_compilation.o: Tuto2_autogen/mocs_compilation.cpp.o

.PHONY : Tuto2_autogen/mocs_compilation.o

# target to build an object file
Tuto2_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Tuto2_autogen/mocs_compilation.cpp.o
.PHONY : Tuto2_autogen/mocs_compilation.cpp.o

Tuto2_autogen/mocs_compilation.i: Tuto2_autogen/mocs_compilation.cpp.i

.PHONY : Tuto2_autogen/mocs_compilation.i

# target to preprocess a source file
Tuto2_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Tuto2_autogen/mocs_compilation.cpp.i
.PHONY : Tuto2_autogen/mocs_compilation.cpp.i

Tuto2_autogen/mocs_compilation.s: Tuto2_autogen/mocs_compilation.cpp.s

.PHONY : Tuto2_autogen/mocs_compilation.s

# target to generate assembly for a file
Tuto2_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/Tuto2_autogen/mocs_compilation.cpp.s
.PHONY : Tuto2_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tuto2.dir/build.make CMakeFiles/Tuto2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tuto2_autogen"
	@echo "... Tuto2"
	@echo "... BServer.o"
	@echo "... BServer.i"
	@echo "... BServer.s"
	@echo "... Bilberry.o"
	@echo "... Bilberry.i"
	@echo "... Bilberry.s"
	@echo "... GPSInfo.o"
	@echo "... GPSInfo.i"
	@echo "... GPSInfo.s"
	@echo "... LCDRange.o"
	@echo "... LCDRange.i"
	@echo "... LCDRange.s"
	@echo "... Menu.o"
	@echo "... Menu.i"
	@echo "... Menu.s"
	@echo "... RGB.o"
	@echo "... RGB.i"
	@echo "... RGB.s"
	@echo "... Tuto2_autogen/mocs_compilation.o"
	@echo "... Tuto2_autogen/mocs_compilation.i"
	@echo "... Tuto2_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

